"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { IoMdFootball } from "react-icons/io";
import Link from "next/link";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="absolute inset-x-0 top-0 bottom-0 bg-gradient-to-r from-[#001730] to-[#004080] text-white max-h-full rounded-md mx-8 my-14 shadow-lg flex gap-10 p-4">
            <div className="flex flex-col">
                <div className="flex gap-2">
                    <IoMdFootball className="text-4xl"/>
                    <p className="text-lg font-bold leading-none">
                        <span className="block">POPUP SURE </span>
                        <span className="block">PREDICTIONS</span>
                    </p>
                </div>
                <div className="flex flex-col items-start gap-2 pt-4 pl-6 font-bold text-lg text-white">
                    <Link href="/home" className={`pb-1 ${ pathname === "/home" ? "border-b-4 border-black font-bold" : "border-b-0"}`}>Home</Link>
                    <Link href="/predictions" className={`inline-block pb-1 ${ pathname === "/predictions"? "border-b-4 border-orange-red font-bold text-orange-red" : "border-b-0 border-orange-red"}`}>Predictions</Link>
                    <Link href={"/statistics"}>Statistics</Link>
                </div>
            </div>
            {children}
        </nav>
      </body>
    </html>
  );
}
